name: Test Continuous Deployment

on:
  push:
    branches:
      - 'release/*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry and dependencies
      run: |
        pip install -U pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Lint with flake8
      run: poetry run flake8 . --ignore=W503,E712,E231,E203 --count --max-complexity=10 --max-line-length=88 --show-source --statistics  --exclude=.git,__pycache__,.venv
    - name: Test with pytest
      run: poetry run pytest tests
    - name: Configure publishing credentials
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - name: Configure PyPI repository
      run: poetry config repositories.test https://test.pypi.org/legacy/
    - name: Build PyPI package
      run: poetry build
    - name: Publish to Test PyPI
      run: poetry publish --repository test
